export { About } from './About';
export { Cta } from './Cta';
export { FAQ } from './FAQ';
export { Features } from './Features';
export { Hero } from './Hero';
export { HowItWorks } from './HowItWorks';
export { Pricing } from './Pricing';
export { Services } from './Services';
export { UserFeedback } from './UserFeedback';